### ISSUE TITLE
:robot: Action --- Automatically test the schematics 

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs2XX-ComputerArchitecture#3]
### What

Have an action run the tests for schematics 

### Why

Confirm correctness

### How

Probably will have to clone the [repo](https://github.com/hneemann/Digital) and then run Digital with the proper args to run the tests. 

### Additional Notes

I expect the tests will be included in the schematics I make that I will run locally. That said, as the builds get more complex, the tests may become difficult to work with. Time will tell.

**Comment by twentylemon** [comment]
> Probably will have to clone the [repo](https://github.com/hneemann/Digital) and then run Digital with the proper args to run the tests.

Could use `actions/checkout` to pull their repo, there's load of options to checkout repos in different directories etc. But, it's only a jar that's needed to run, so most straightforward is probably to keep that jar in this repo and use it to test. Keeps this safe from any external changes (their repo going private, downloads disappearing, whatever), and you keep a copy of the jar to """distribute""" in those extreme cases.

If you wanna go overboard, could add a separate action on a cron schedule to pull the newest version of their jar, commit it, and open a PR. Home brew dependabot.
